### ISSUE TITLE
Why didn't the usdc mentioned by L2 reach the account?

### ISSUE THREAD

**Issue by zwjun668** [celer-network/layer2-finance-contracts#101]
The withdrawal of usdc from L2 to L1 has not reached the account. What is the reason? Can you help me out? More than 13 hours, thank you!
<img width="1070" alt="微信图片_20211121231400" src="https://user-images.githubusercontent.com/90258877/142771690-4f4c8858-74df-4995-808d-89b20a659afc.png">
<img width="1051" alt="微信图片_20211121231406" src="https://user-images.githubusercontent.com/90258877/142771693-e3957304-0b33-42a3-89ae-c5ce592b53c8.png">

**Comment by Dominator008** [comment]
Hi, our submitter service had a little hiccup. Your withdrawal should be confirmed now. Sorry for the waiting.
